spring:
    application:
        name: homeassistant-proxy

homeassistant:
    shares:
        -   name: "Garagentor"
            apiKey: "abcd1234"
            allowedEntities:
                - cover.garage_door