name: "Master Pipeline"

on:
    push:
        branches:
            - master

jobs:
    test:
        name: Test Code
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@v4
                name: Checkout Code
            -   name: Set up JDK 21 for x64
                uses: actions/setup-java@v4
                with:
                    java-version: '21'
                    distribution: 'temurin'
                    architecture: x64
            -   name: Setup Gradle
                uses: gradle/actions/setup-gradle@v4
            -   name: Lint with ktlint
                run: ./gradlew lintKotlin
            -   name: Run Tests
                run: ./gradlew test
    package:
        name: Package Backend
        runs-on: ubuntu-latest
        needs:
            - test
        steps:
            -   uses: actions/checkout@v4
                name: Checkout Code
            -   name: Login to GHCR
                uses: docker/login-action@v3
                with:
                    registry: ghcr.io
                    username: ${{ github.actor }}
                    password: ${{ secrets.GITHUB_TOKEN }}
            -   name: Set up JDK 21 for x64
                uses: actions/setup-java@v4
                with:
                    java-version: '21'
                    distribution: 'temurin'
                    architecture: x64
            -   name: Setup Gradle
                uses: gradle/actions/setup-gradle@v4
            -   name: Build and push docker images
                run: ./gradlew dockerPushImage